# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn2'
    subscriptionId: '195f646c-95ce-429c-a46b-9e60f6fe4a4a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMPipeline-rg'
    location: 'South Africa North'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ThulasCloud/ARMPipeline-repo2/main/create_web_app/azuredeploy.json?token=GHSAT0AAAAAACXCEXO7ZM4KRK2ZT54ZMOMWZWZTUTA'
    overrideParameters: '-projectName ARMPipeline-repo2'
    deploymentMode: 'Incremental'